[project]
name = "my-package"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.32.4",
]

[dependency-groups]
dev = [
    "mypy>=1.17.1",
    "pytest>=8.4.1",
    "ruff>=0.12.8",
]
